enum authorities {
  DEFAULT = "DEFAULT",
  USER_MODIFY = "USER_MODIFY",
  USER_MODIFY_SELF = "USER_MODIFY_SELF",
  USER_DELETE = "USER_DELETE",
  USER_DELETE_SELF = "USER_DELETE_SELF",
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_READ_BY_ID = "USER_READ_BY_ID",
  BLOG_READ = "BLOG_READ",
  BLOG_MODIFY = "BLOG_MODIFY",
  BLOG_MODIFY_BY_ID = "BLOG_MODIFY_BY_ID",
  BLOG_DELETE = "BLOG_DELETE",
  BLOG_DELETE_BY_ID = "BLOG_DELETE_BY_ID",
  BLOG_CREATE = "BLOG_CREATE"
}
export default authorities;
