enum authorities {
  DEFAULT = "DEFAULT",
  USER_MODIFY = "USER_MODIFY",
  USER_DELETE = "USER_DELETE",
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  BLOG_READ = "BLOG_READ",
  BLOG_MODIFY = "BLOG_MODIFY",
  BLOG_DELETE = "BLOG_DELETE",
  BLOG_CREATE = "BLOG_CREATE"
}
export default authorities;
